s= "Tops Technologies"

print(len(s))
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print(s.center(40,"*"))
print(s.count("o"))
print(s.endswith("es"))
print(s.startswith("to"))
print(s.find("log"))
print(s.index("T",3))
print("tops123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(" ".isspace())
print("Python Programing".istitle())
print("python".islower())
print("Hello".replace("l","w"))